# Generated by Django 4.0.4 on 2022-07-19 15:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ganre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('боевик', 'Боевик'), ('комедия', 'Комедия'), ('триллер', 'Триллер'), ('ужасы', 'Ужасы'), ('детектив', 'Детектив'), ('драма', 'Драма'), ('фэнтези', 'Фэнтези'), ('фантастика', 'Фантастика'), ('приключения', 'Приключения'), ('криминал', 'Криминал'), ('мелодрама', 'мелодрама')], max_length=25, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='lim_age',
            field=models.CharField(choices=[('3', '3+'), ('12', '12+'), ('16', '16+'), ('18', '18+')], default='1', max_length=50, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tipe_film',
            field=models.CharField(choices=[('film', 'Фильм'), ('serial', 'Сериал'), ('multfilm', 'Мультфильм')], default='film', max_length=50, verbose_name='Тип фильма'),
        ),
    ]
