# Generated by Django 4.0.4 on 2022-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_film_ganre_alter_film_image_alter_film_lim_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Картинка'),
        ),
    ]
