# Generated by Django 4.0.4 on 2022-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tipe_film',
            field=models.CharField(choices=[('movie', 'Фильм'), ('tv-series', 'Сериал'), ('animated-series', 'Мультфильм')], default='film', max_length=50, verbose_name='Тип фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
    ]
