# Generated by Django 4.0.4 on 2022-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_film_lim_age_alter_film_tipe_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='lim_age',
            field=models.CharField(choices=[('0', '16+'), ('3', '3+'), ('6', '6+'), ('12', '12+'), ('16', '16+'), ('18', '18+')], default='16', max_length=50, verbose_name='Возрастной рейтинг'),
        ),
    ]
