# Generated by Django 4.0.4 on 2022-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_film_lim_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='core.actor'),
        ),
    ]
