# Generated by Django 4.0.4 on 2022-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_film_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(to='core.actor'),
        ),
    ]
