# Generated by Django 4.0.4 on 2022-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_film_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, related_name='director', to='core.director'),
        ),
    ]
