# Generated by Django 4.0.4 on 2022-05-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ganre', models.CharField(choices=[('1', 'Боевик'), ('2', 'Комедия'), ('3', 'Триллер'), ('4', 'Ужасы')], max_length=50, verbose_name='Жанр')),
                ('tipe_film', models.CharField(choices=[('1_type', 'film'), ('2_type', 'serial'), ('3_type', 'mult')], default='1_type', max_length=50, verbose_name='Тип фильма')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('lim_age', models.CharField(choices=[('1', '3+'), ('2', '12+'), ('3', '16+'), ('4', '18+')], default='1', max_length=50, verbose_name='Возрастной рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('comment_author', models.CharField(default='Ваше имя', max_length=50, verbose_name='Имя автора комментария')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Cinema_app.film')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('film', models.ManyToManyField(to='Cinema_app.film')),
            ],
        ),
    ]
