# Generated by Django 4.0.4 on 2022-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, default='q', max_length=50, null=True, verbose_name='Страна'),
        ),
    ]
