# Generated by Django 4.0.4 on 2022-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actor_name',
        ),
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='actor', to='Cinema_app.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='director', to='Cinema_app.director'),
        ),
    ]
