# Generated by Django 4.0.4 on 2022-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tipe_film',
            field=models.CharField(choices=[('film', 'Фильм'), ('serial', 'Сериал'), ('multfilm', 'Мультфильм')], default='1_type', max_length=50, verbose_name='Тип фильма'),
        ),
    ]
