# Generated by Django 4.0.4 on 2022-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0002_remove_film_actor_name_film_actor_film_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
