# Generated by Django 4.0.4 on 2022-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0003_remove_film_poster_film_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
