# Generated by Django 4.0.4 on 2022-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0005_remove_actor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(null=True, upload_to='', verbose_name='Постер'),
        ),
    ]
