# Generated by Django 4.0.4 on 2022-05-26 14:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0006_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='ganre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Боевик'), ('2', 'Комедия'), ('3', 'Триллер'), ('4', 'Ужасы')], max_length=50, verbose_name='Жанр'),
        ),
    ]
