# Generated by Django 4.0.4 on 2022-05-31 15:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0007_alter_film_ganre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=50, verbose_name='Имя автора комментария'),
        ),
        migrations.AlterField(
            model_name='film',
            name='ganre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Боевик'), ('2', 'Комедия'), ('3', 'Триллер'), ('4', 'Ужасы')], max_length=5, verbose_name='Жанр'),
        ),
    ]
