# Generated by Django 4.0.4 on 2022-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0008_alter_comment_comment_author_alter_film_ganre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер'),
        ),
    ]
