# Generated by Django 4.0.4 on 2022-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema_app', '0010_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
